### ISSUE TITLE
Support ssh-agent

### ISSUE THREAD

**Issue by puce77** [trajano/wagon-git#6]
It seems ssh-agent is not supported.

Please add support for ssh-agent so you don't have to store the passphrase in the settings.xml file.

**Comment by trajano** [comment]
See https://gist.github.com/quidryan/5449155 for hints

**Comment by trajano** [comment]
Seems like it is not yet resolved in Eclipse https://bugs.eclipse.org/bugs/show_bug.cgi?id=179924

**Comment by trajano** [comment]
I have deployed  2.0.4-SNAPSHOT @ https://oss.sonatype.org/content/repositories/snapshots/net/trajano/wagon/wagon-git/2.0.4-SNAPSHOT/ with this feature, pls confirm it works for you so I can create a proper release.

**Comment by puce77** [comment]
In a KDE Konsole, if I run:
```
ssh -T git@github.com
```
the first time, KDE will ask me about the passphrase.
Afterwards everything the command runs without asking for a passphrase anymore.

Calling 
```
mvn site-deploy 
```
however (using your wagon-git v2.0.4-SNAPSHOT) causes some issues.

If the settings.xml looks like this:
        <server>
            <id>ssh</id>
        </server>

Then I'm getting the following error:

> Error uploading site: ssh://git@github.com/myProject: reject HostKey: github.com -> [Help 1]


If the settings.xml looks like this:
        <server>
            <id>ssh</id>
            <username>git</username>
        </server>

Then I'm getting the following error:

> Execution default-deploy of goal org.apache.maven.plugins:maven-site-plugin:3.4:deploy failed: ssh://git@github.com:22: org.eclipse.jgit.transport.CredentialItem$YesNoType:The authenticity of host 'github.com' can't be established.

But as I said `ssh -T git@github.com` runs fine.

Do I have to use some other configuration?

**Comment by trajano** [comment]
Is github allowed in your known hosts for your agent.

**Comment by puce77** [comment]
I think so.
github.com appears in .ssh/known_hosts (Kubuntu)

And the following commands work without issues:
''''
ssh -T git@github.com
''''
and
''''
git push git@github.com:someRepo
''''
Is there anything other I should set? Maybe something Maven specific?

**Comment by trajano** [comment]
Maybe it is using a different agent protocol than the one I used.

**Comment by puce77** [comment]
What configuration did you use in the settings.xml file?

**Comment by trajano** [comment]
I just copied the code I don't have a test for agent usage. If it does not work then I can just leave it off and wait for someone to contribute a patch.

**Comment by puce77** [comment]
Hmm, the thing is, I think it's really bad to have the passphrase stored in a file. I think it's even worse than storing passwords in a file. I tried to use username/ password instead, but the wagon wants the passphrase:
```
failed: ssh://git@github.com:22: org.eclipse.jgit.transport.CredentialItem$StringType:Passphrase for /home/puce/.ssh/id_rsa -> [Help 1]
```
That is with version 2.0.3

As far as I can see, the README says this should work: https://github.com/trajano/wagon-git

But then I had a look at the source code, and it seems ssh:// is always used: https://github.com/trajano/wagon-git/blob/master/src/main/java/net/trajano/wagon/git/GitHubPagesWagon.java

**Comment by trajano** [comment]
GitHub does not support user ID and password for their ssh connections from what I know. 




They need you to upload a private key.

**Comment by puce77** [comment]
They do support https URLs which work with username/password: https://help.github.com/articles/which-remote-url-should-i-use/

Check the clone URL, there you can switch from ssh to https.

Also it would be great to override this on the command line, e.g. -Dusername=x -Dpassword=y

Depending on the aggregated information gathered from the settings.xml and the command line you could decide if the ssh URL should be used (e.g. username = git or no username) or the https URL should be used (e.g. username != git and password both set)

And maybe consider using privateKey/ passphrase for ssh instead of username/password: https://maven.apache.org/settings.html#Servers

**Comment by trajano** [comment]
The wagon git does not support the HTTPS approach.
